
services:
  typo3:
    image: brutalbirdie/typo3:13.4.1
    container_name: typo3
    volumes:
      - typo3-data:/var/www/html/
    networks:
      - typo3
      - mariadb
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "echo", "READY"]
      start_period: 5s
      interval: 10s
      timeout: 5s
      retries: 3
  mariadb:
    image: mariadb:10-jammy
    container_name: maridadb
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: typo3
      MARIADB_USER: typo3
      MARIADB_PASSWORD: typo3
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - mariadb
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
  nginx:
    image: nginx:1.27.4
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - typo3-data:/var/www/html/
      - ./docker/etc/nginx/conf.d/typo3_nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - typo3
    depends_on:
      typo3:
        condition: service_healthy

volumes:
  typo3-data:
  db-data:

networks:
  mariadb:
  typo3:
