version: "3"

services:
  web:
    image: "ochorocho/typo3-container:v12"
    depends_on:
      - mariadb
    restart: 'always'
    ports:
      - '8080:80'
    links:
      - mariadb
  mariadb:
    image: "mariadb:10.7"
    restart: 'always'
#    environment:
#      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
#      MYSQL_DATABASE: "${MYSQL_DATABASE}"
#      MYSQL_USER: "${MYSQL_USER}"
#      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
