server {
    listen       80;
    server_name  _;
    root         /var/www/html/public/;

    fastcgi_param REQUEST_METHOD $request_method;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_index index.php;

    access_log /var/log/nginx/example.journaldev.com-access.log;
    error_log  /var/log/nginx/example.journaldev.com-error.log error;
    index index.php;

    location /typo3 {
        rewrite ^ /typo3/;
    }

    location /typo3/ {
        absolute_redirect on;
        try_files $uri /typo3/index.php$is_args$args;
    }

    if (!-e $request_filename) {
        rewrite ^/(.+)\.(\d+)\.(php|js|css|png|jpg|gif|gzip)$ /$1.$3 last;
    }

    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php$ {
        fastcgi_pass typo3:9000;
    }
}