name: Build

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 4 * * *"

jobs:
  build:
    name: Build Container
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v3
      -
        name: Install composer
        uses: php-actions/composer@v6
        with:
          php_version: "8.2"
      -
        name: Docker info
        run: docker info
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64
      -
        name: "TYPO3 v13"
        shell: 'script -q -e -c "bash {0}"'
        run: ./bin/t3-container build ochorocho/typo3-container v13 --php 8.3 -x -p
      -
        name: "TYPO3 v12"
        shell: 'script -q -e -c "bash {0}"'
        # Additionally, require typo3/cms-webhooks and typo3/cms-reactions because these are not available in < v12
        run: ./bin/t3-container build ochorocho/typo3-container v12 -x -p
      -
        name: "TYPO3 v11"
        shell: 'script -q -e -c "bash {0}"'
        run: ./bin/t3-container build ochorocho/typo3-container v11 -x -p
