name: Build

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 4 * * *"

jobs:
  build:
    name: Build
    strategy:
      matrix:
        include:
          - TYPO3: dev-main
            PHP: 8.3
            OS: ubuntu-24.04
          - TYPO3: v13
            PHP: 8.3
            OS: ubuntu-24.04
          - TYPO3: v12
            PHP: 8.2
            OS: ubuntu-24.04
#          - TYPO3: v11
#            PHP: 8.1
#            OS: ubuntu-20.04
    runs-on:
      labels: ubuntu-24.04-16core
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v3
      -
        name: Install composer
        uses: php-actions/composer@v6
        with:
          php_version: "8.4"
      -
        name: Docker info
        run: docker info
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      -
        name: "TYPO3 ${{ matrix.TYPO3 }} - PHP ${{ matrix.PHP }}"
        shell: 'script -q -e -c "bash {0}"'
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          ./bin/t3-container build ochorocho/typo3-container ${{ matrix.TYPO3 }} --php ${{ matrix.PHP }} -x -p
