name: Build

on:
  push:
  pull_request:
  schedule:
    - cron: "0 4 * * *"

jobs:
  build:
    name: Build Container
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v3
      -
        name: Docker info
        run: docker info
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64
      -
        name: "TYPO3 latest"
        run: ./t3-container -x -p
        shell: bash
      -
        name: "TYPO3 v12"
        run: ./t3-container -v v12 -x -p
        shell: bash
      -
        name: "TYPO3 v11"
        run: ./t3-container -v v11 -x -p
        shell: bash
