name: v12

on:
  push:
  pull_request:
  schedule:
    - cron: "0 4 * * *"
jobs:
  docker:
    name: Docker Image Builder
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: docker-practice/actions-setup-docker@master
      - run: |
          set -x
          docker version
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64,linux/arm64
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ochorocho/typo3-container
          tags: |
            type=raw,value=v12,enable=true
      - name: Build docker image
        run: ./t3-container -v v10

